"""Style preset data for palette generation. Each preset biases hue ranges, vibrancy, contrast, warmth."""

STYLE_PRESETS = {
    "general": {
        "hue_ranges": None,  # all hues allowed
        "vibrancy_mod": 0.0,
        "contrast_mod": 0.0,
        "warmth_mod": 0.0,
        "preferred_harmonies": ["analogous", "complementary", "triadic", "split_complementary"],
        "forbidden_names": set(),
        "neutral_bias": ["cream", "charcoal-gray", "beige", "white", "black"],
    },
    "beach": {
        "hue_ranges": [(170, 220), (30, 60), (0, 30)],  # aqua/blue, sandy, coral
        "vibrancy_mod": 0.1,
        "contrast_mod": -0.1,
        "warmth_mod": 0.15,
        "preferred_harmonies": ["analogous", "split_complementary"],
        "forbidden_names": {"charcoal-gray", "black", "espresso"},
        "neutral_bias": ["sand", "cream", "ivory", "linen", "off-white"],
    },
    "urban_streetwear": {
        "hue_ranges": None,
        "vibrancy_mod": 0.15,
        "contrast_mod": 0.2,
        "warmth_mod": -0.1,
        "preferred_harmonies": ["complementary", "tetradic", "triadic"],
        "forbidden_names": {"pastel-pink", "pastel-yellow", "pastel-purple", "pastel-blue"},
        "neutral_bias": ["black", "charcoal-gray", "white", "medium-gray"],
    },
    "evening_gala": {
        "hue_ranges": [(0, 20), (260, 310), (330, 360), (220, 250)],
        "vibrancy_mod": 0.1,
        "contrast_mod": 0.15,
        "warmth_mod": 0.0,
        "preferred_harmonies": ["complementary", "split_complementary", "analogous"],
        "forbidden_names": {"lime", "chartreuse", "neon-green", "neon-yellow", "neon-orange"},
        "neutral_bias": ["black", "ivory", "champagne", "charcoal-gray"],
    },
    "casual_daywear": {
        "hue_ranges": None,
        "vibrancy_mod": -0.1,
        "contrast_mod": -0.1,
        "warmth_mod": 0.05,
        "preferred_harmonies": ["analogous", "monochromatic", "split_complementary"],
        "forbidden_names": {"neon-green", "neon-yellow", "neon-pink", "neon-orange", "neon-blue",
                            "electric-blue", "electric-purple"},
        "neutral_bias": ["cream", "beige", "oatmeal", "soft-gray", "linen"],
    },
    "vintage_retro": {
        "hue_ranges": [(0, 50), (150, 200), (320, 360)],
        "vibrancy_mod": -0.15,
        "contrast_mod": -0.05,
        "warmth_mod": 0.1,
        "preferred_harmonies": ["analogous", "complementary", "triadic"],
        "forbidden_names": {"neon-green", "neon-yellow", "neon-pink", "neon-orange", "neon-blue",
                            "electric-blue", "electric-purple"},
        "neutral_bias": ["cream", "ivory", "oatmeal", "mushroom", "taupe"],
    },
    "cyberpunk_neon": {
        "hue_ranges": [(170, 220), (260, 330), (50, 70)],
        "vibrancy_mod": 0.35,
        "contrast_mod": 0.25,
        "warmth_mod": -0.2,
        "preferred_harmonies": ["complementary", "triadic", "tetradic"],
        "forbidden_names": {"beige", "oatmeal", "linen", "cream", "ivory"},
        "neutral_bias": ["black", "charcoal-gray", "medium-gray"],
    },
    "pastel_dream": {
        "hue_ranges": None,
        "vibrancy_mod": -0.2,
        "contrast_mod": -0.2,
        "warmth_mod": 0.05,
        "preferred_harmonies": ["analogous", "triadic", "split_complementary"],
        "forbidden_names": {"black", "charcoal-gray", "espresso", "maroon"},
        "neutral_bias": ["soft-white", "ivory", "cream", "pastel-gray", "linen"],
    },
    "earthy_natural": {
        "hue_ranges": [(10, 50), (70, 150), (0, 15)],
        "vibrancy_mod": -0.15,
        "contrast_mod": -0.05,
        "warmth_mod": 0.2,
        "preferred_harmonies": ["analogous", "monochromatic", "split_complementary"],
        "forbidden_names": {"neon-green", "neon-yellow", "neon-pink", "neon-orange", "neon-blue",
                            "electric-blue", "electric-purple", "hot-pink", "magenta", "fuchsia"},
        "neutral_bias": ["taupe", "mushroom", "sand", "oatmeal", "khaki"],
    },
    "monochrome_chic": {
        "hue_ranges": [(0, 360)],
        "vibrancy_mod": -0.3,
        "contrast_mod": 0.2,
        "warmth_mod": 0.0,
        "preferred_harmonies": ["monochromatic", "analogous"],
        "forbidden_names": set(),
        "neutral_bias": ["black", "white", "charcoal-gray", "medium-gray", "light-gray"],
    },
    "tropical": {
        "hue_ranges": [(0, 40), (80, 180), (300, 340)],
        "vibrancy_mod": 0.25,
        "contrast_mod": 0.1,
        "warmth_mod": 0.15,
        "preferred_harmonies": ["complementary", "triadic", "tetradic"],
        "forbidden_names": {"charcoal-gray", "slate-gray", "medium-gray", "espresso"},
        "neutral_bias": ["cream", "sand", "ivory", "white", "linen"],
    },
    "winter_cozy": {
        "hue_ranges": [(0, 30), (200, 260), (330, 360)],
        "vibrancy_mod": -0.1,
        "contrast_mod": 0.05,
        "warmth_mod": 0.1,
        "preferred_harmonies": ["analogous", "complementary", "monochromatic"],
        "forbidden_names": {"neon-green", "neon-yellow", "neon-pink", "neon-orange", "neon-blue",
                            "lime", "chartreuse"},
        "neutral_bias": ["cream", "ivory", "oatmeal", "charcoal-gray", "espresso"],
    },
    "festival": {
        "hue_ranges": None,
        "vibrancy_mod": 0.3,
        "contrast_mod": 0.15,
        "warmth_mod": 0.0,
        "preferred_harmonies": ["triadic", "tetradic", "complementary"],
        "forbidden_names": set(),
        "neutral_bias": ["black", "white", "cream", "charcoal-gray"],
    },
    "office_professional": {
        "hue_ranges": [(200, 260), (0, 15), (330, 360)],
        "vibrancy_mod": -0.2,
        "contrast_mod": 0.1,
        "warmth_mod": -0.05,
        "preferred_harmonies": ["analogous", "monochromatic", "complementary"],
        "forbidden_names": {"neon-green", "neon-yellow", "neon-pink", "neon-orange", "neon-blue",
                            "electric-blue", "electric-purple", "hot-pink", "magenta", "lime",
                            "chartreuse", "bubblegum"},
        "neutral_bias": ["charcoal-gray", "white", "ivory", "slate-gray", "black"],
    },
}
